name: GitHub Project Metrics
description: GitHubのIssueやProjectの情報を取得してチームの生産性を計測

inputs:
  github-token: # GitHub token for API access
    description: GitHub token for accessing repository data
    required: true
  project-scope: # Project取得のスコープ
    description: Project取得のスコープ（user, organization）
    required: true
  organization-name: # 組織名（organizationスコープの場合）
    description: 組織名（project-scopeがorganizationの場合に必須）
    required: false
  output-path: # JSONファイルの出力先
    description: JSONファイルの出力先ディレクトリ（デフォルトはGitHubワークスペース）
    required: false

outputs:
  issues: # id of output
    description: JSON形式で取得したIssueデータ（整形済み）
  raw-issues: # id of output
    description: JSON形式で取得したIssueデータ（整形前の生データ）
  issue-count: # id of output
    description: 取得したIssueの総数
  projects: # id of output
    description: JSON形式で取得したProjectデータ（整形済み）
  raw-projects: # id of output
    description: JSON形式で取得したProjectデータ（整形前の生データ）
  project-count: # id of output
    description: 取得したProjectの総数
  total-tasks: # id of output
    description: 全Projectのタスク総数

runs:
  using: node20
  main: dist/index.js
