name: GitHub Project Metrics
description: GitHubのIssueやProjectの情報を取得してチームの生産性を計測

inputs:
  github-token: # GitHub token for API access
    description: GitHub token for accessing repository data
    required: true

outputs:
  issues: # id of output
    description: JSON形式で取得したIssueデータ
  issue-count: # id of output
    description: 取得したIssueの総数

runs:
  using: node20
  main: dist/index.js
