# .github/ISSUE_TEMPLATE/documentation.yml

name: 📖 ドキュメントの改善提案
description: ドキュメントの誤字脱字、分かりにくい表現、内容の追加などを提案します
title: "[Docs] "
labels: ["doc"]
assignees:
  -

body:
  - type: markdown
    attributes:
      value: |
        ドキュメント改善のご協力ありがとうございます！
        より良いドキュメントにするため、以下の項目にご記入ください。

  - type: input
    id: target-document
    attributes:
      label: 対象のドキュメントはどこですか？
      description: 改善を提案したいドキュメントのURLやファイルパスを記入してください。
      placeholder: 例） /docs/getting-started.md または https://example.com/docs/api
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: どのような問題がありますか？
      description: 誤字脱字、分かりにくい表現、情報が古い、内容が不足しているなど、具体的に教えてください。
      placeholder: 例）「インストール」のセクションで、〇〇のコマンドが古いバージョンのままになっている。
    validations:
      required: true

  - type: textarea
    id: suggested-improvement
    attributes:
      label: どのように改善することを提案しますか？
      description: 具体的な修正案を記述してください。「〇〇を△△に修正する」のように、Before/Afterが分かると助かります。
      placeholder: |
        （誤）`npm install old-package`
        （正）`npm install new-package`
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: その他 (追加のコンテキスト)
      description: なぜこの改善が必要だと思うか、背景や参考になる情報があればこちらに記入してください。（任意）
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: 確認事項
      description: Issueを立てる前に、以下の項目を確認してください。
      options:
        - label: 既存のIssueを検索し、同様の提案がないことを確認しました。
          required: true