# .github/ISSUE_TEMPLATE/task.yml

name: ⚙️ タスク (Task)
description: リファクタリング、CI/CD改善、依存関係の更新など、開発者向けのタスクを管理します
title: "[Task] "
labels: ["task"]
assignees:
  -

body:
  - type: markdown
    attributes:
      value: |
        プロジェクトの改善にご協力いただきありがとうございます。
        このIssueでは、機能開発やバグ修正以外のタスクを管理します。

  - type: dropdown
    id: task-type
    attributes:
      label: タスクの種類
      description: このタスクが最も近いカテゴリを選択してください。
      options:
        - "♻️ リファクタリング / 技術的負債の返済"
        - "🚀 CI / CD の改善"
        - "📦 依存関係の更新 (ライブラリアップデート)"
        - "🔐 セキュリティ対応"
        - "🛠️ リポジトリ設定 / 権限管理"
        - "🚀 リリース作業"
        - "🧹 その他 (雑務など)"
    validations:
      required: true

  - type: textarea
    id: purpose
    attributes:
      label: 目的・背景
      description: なぜこのタスクが必要ですか？ 解決したい課題や経緯を具体的に記述してください。
      placeholder: |
        例1 (リファクタリング): 〇〇コンポーネントが複雑化し、テストが困難になっているため、責務を分割して可読性を向上させたい。
        例2 (依存関係): △△ライブラリにセキュリティ脆弱性が発見されたため、最新バージョンに更新する必要がある。
    validations:
      required: true

  - type: textarea
    id: todo-list
    attributes:
      label: タスクの詳細・やることリスト (To-Do)
      description: このタスクを完了するために必要な具体的な作業を、Markdownのチェックリスト形式で記述してください。
      value: |
        - [ ] 
        - [ ] 
        - [ ] 
      render: markdown
    validations:
      required: true

  - type: textarea
    id: definition-of-done
    attributes:
      label: 完了の定義 / 期待される効果 (任意)
      description: どのような状態になったらこのタスクは完了とみなせますか？また、どのような効果を期待していますか？
      placeholder: |
        - 既存のテストがすべてパスする
        - パフォーマンスが〇〇%改善される
        - Code ClimateのスコアがB以上になる
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 補足事項 (任意)
      description: 参考URL、関連Issue、注意点などがあれば記述してください。
    validations:
      required: false