on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  get_metrics_job:
    name: Get Repository Metrics
    runs-on: ubuntu-latest

    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get Repository Metrics
        uses: ./ # Uses an action in the root directory
        id: get-metrics
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          project-scope: "user"  # user または organization
          # organization-name: "YUKIKEDA"  # organizationスコープの場合に指定

      # Use the output from the `get-metrics` step
      - name: Display Metrics Count
        run: |
          echo "Total issues: ${{ steps.get-metrics.outputs['issue-count'] }}"
          echo "Total projects: ${{ steps.get-metrics.outputs['project-count'] }}"
          echo "Total tasks: ${{ steps.get-metrics.outputs['total-tasks'] }}"

      - name: Display Raw Issues Data
        run: |
          echo "=== Raw Issues Data (Unformatted) ==="
          echo '${{ steps.get-metrics.outputs['raw-issues'] }}' | jq . || echo '${{ steps.get-metrics.outputs['raw-issues'] }}'
          echo "======================================="

      - name: Display Raw Projects Data
        run: |
          echo "=== Raw Projects Data (Unformatted) ==="
          echo '${{ steps.get-metrics.outputs['raw-projects'] }}' | jq . || echo '${{ steps.get-metrics.outputs['raw-projects'] }}'
          echo "======================================="

      - name: Display Formatted Projects Data
        run: |
          echo "=== Formatted Projects Data ==="
          echo '${{ steps.get-metrics.outputs['projects'] }}' | jq . || echo '${{ steps.get-metrics.outputs['projects'] }}'
          echo "=============================="

      - name: List Generated Files
        run: |
          ls -la *.json || echo "No JSON files found"
          echo "JSON files are automatically generated by the action"
