on:
  push:
    branches:
      - main

jobs:
  get_issues_job:
    name: Get Repository Issues
    runs-on: ubuntu-latest

    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get Repository Issues
        uses: ./ # Uses an action in the root directory
        id: get-issues
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Use the output from the `get-issues` step
      - name: Display Issue Count
        run: |
          echo "Total issues: ${{ steps.get-issues.outputs['issue-count'] }}"

      - name: Save Issues to File
        run: |
          echo '${{ steps.get-issues.outputs.issues }}' > issues.json
          echo "Issues saved to issues.json"
