on:
  push:
    branches:
      - main
      - 'feat-*'
  workflow_dispatch:

jobs:
  get_metrics_job:
    name: Get Repository Metrics
    runs-on: ubuntu-latest

    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get Repository Metrics
        uses: ./ # Uses an action in the root directory
        id: get-metrics
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          project-scope: "user"  # user または organization
          # organization-name: "YUKIKEDA"  # organizationスコープの場合に指定

      # 結果はSummaryセクションに自動的に表示されます
